<?php
$kalkulation = array(
    array(
        'kalkulation1',
        'ek-erstellen',
        'einkauf.svg',
        'Frosch',
        'Einkaufskalkulation',
    ),
    array(
        'kalkulation2',
        'ik-erstellen',
        'intern.svg',
        'Känguru',
        'Internekalkulation',
    ),
    array(
        'kalkulation3',
        'vk-erstellen',
        'verkauf.svg',
        'Hase',
        'Verkaufskalkulation'
    ),
    array(
        'kalkulation4',
        'gk-erstellen',
        'gesamt.svg',
        'Hirsch',
        'Gesamtkalkulation',
    ),
);