<?php
$nav = array(
    array('home',
                'home.svg',
                'Startseite',
                'Startseite',
    ),
    array('neues-konto',
                'neues-konto.svg',
                'Neues Konto',
                'Neues Konto',
    ),
    array('bilanz',
                'bilanz.svg',
                'Bilanz',
                'Bilanz',
    ),
    array('erfolgsrechnung',
                'erfolgsrechnung.svg',
                'Erfolgsrechnung',
                'Erfolgsrechnung',
    ),
    array('jahresabschluss',
                'jahresabschluss.svg',
                'Jahresabschluss',
                'Jahresabschluss',
    ),
    array('kalkulation',
                'kalkulation.svg',
                'Kalkulation',
                'Kalkulation',
    ),
);