<?php
include('app/Controllers/inc/arrays/alle_konten.inc.php');

$array = array(
    array(
        'journal1',
        'date',
        'Datum',
        'journal2',
        'date',
    ),
    array(
        'journal3',
        'soll',
        'Soll',
        'journal4',
        '',
    ),
    array(
        'journal5',
        'haben',
        'Haben',
        'journal6',
        '',
    ),
    array(
        'journal7',
        'betrag',
        'Betrag',
        'journal8',
        'number',
    ),
);