<?php
$welcome = array(
    array('neues-konto',
                'goToNeuesKonto()',
                'NeuesKonto.svg',
                'kleines Küken',
                'Neues Konto',
    ),
    array('bilanz',
                'goToBilanz()',
                'Bilanz.svg',
                'Huhn',
                'Bilanz',
    ),
    array('erfolgsrechnung',
                '',
                'Erfolgsrechnung.svg',
                'Pfau',
                'Erfolgsrechnung',
    ),
    array('',
                '',
                'Jahresabschluss.svg',
                'Elefant',
                'Jahresabschluss',
    ),
    array('kalkulation',
                '',
                'Kalkulation.svg',
                'Chamäleon',
                'Kalkulationen',
    ),
);